### PR TITLE
Grafana & Kubernetes pronunciation corrected

### LINKED ISSUE #297: Incorrect phonemes for Grafana and Kubernetes
I hear /gɹə ˈfɑːn ˌɑː/ [ɡʷɹ̠ʷə ˈfɑ̃ːn ˌɑː] and /ˈkuːb ə˞ ˌnet iz/ [ˈkʰʊu̯b ɹ̠̩ ˌnɛɾ iːz] for the two words. Try compare:

- Grafana v.s. Tatjana
- Kubernetes v.s. diabetes v.s. treaties

Also see https://github.com/b1f6c1c4/programming-pronunciations-en_US/commit/7ebcb599f4cebd581a762850fe3a70e75ade188c

### PR DESCRIPTION
**Pull request by IoriOikawa**
Fixes #297

### CODE REVIEW

**Comment by b1f6c1c4** [comment]
@yuanchen8911 Please give it a look.

**Comment by yuanchen8911** [comment]
Thanks for the corrections!

**Pull request merged**
